### ISSUE TITLE
Hyperclick opens duplicate tab

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#1022]
### Issue and Steps to Reproduce
As of some recent version of Nuclide, Hyperclick now opens a duplicate tab if jumping to a method that's in the same file. To elaborate, if I'm in `MyTest.js` and there's a reference to `this.doThings`, using Hyperclick on that method call will open `MyTest.js` again in a second tab and show the `doThings` definition.

### Expected Behavior
Editor should just scroll to the `doThings`, not open a duplicate tab.

### Actual Behavior
A 2nd tab is opened for the same file.

### Versions
* Atom: 1.14.1
* Nuclide: 0.205.0
* Client OS: Mac OS 10.12.3

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (25) /Users/samh/.atom/packages
├── autocomplete-modules@1.6.7
├── expose@0.13.0
├── git-time-machine@1.5.6
├── haskell-grammar@0.4.0
├── highlight-selected@0.12.0
├── js-refactor@0.7.5
├── language-babel@2.54.1
├── language-graphql@0.8.0
├── language-ini@1.17.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@1.11.21
├── linter-eslint@8.1.1
├── merge-conflicts@1.4.4
├── minimap@4.26.8
├── nuclide@0.205.0
├── nuclide-format-js@0.0.36
├── nuclide-test-runner-jest@0.3.0
├── refactor@0.11.3
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── todo-show@1.9.0
└── tool-bar@1.0.1
```

**Comment by abdulhannanali** [comment]
@ffxsam I am running Ubuntu 16.04, Does this seem something that's OS specific or not?

**Comment by nmote** [comment]
I haven't seen this happen, but Atom 1.14 did change the way it handles symlinks. It used to canonicalize paths for text editors, and now it does not. However, Flow still canonicalizes paths. So, I wonder if you have symlinks in your project path. You may be opening `/path/through/symlink/MyTest.js`. Then Flow tells us that the symbol you are navigating to is defined in `/canonical/path/MyTest.js` so we open a new editor.

Before, Atom would have used the canonical path for the editor, so it would have known not to open a new one.

This is just speculation, I haven't actually reproduced this issue. Let me know if this sounds right.

**Comment by ffxsam** [comment]
@nmote I think you nailed it. I was using symlinks for my project folder, and I just stopped doing that.. now it seems fine.

**Comment by nmote** [comment]
Unfortunately I don't have a great solution here other than to stop using symlinks. After some discussion we realized that in order to have a consistent experience, every tool in the stack has to subscribe to the same symlink philosophy (either always canonicalize or never canonicalize). Given the number of tools we integrate with, that seems unlikely to happen.

There are a number of things we could do to hack around simple cases but they all have caveats and it seems like they would overall just increase confusion and add more opportunities for bugs. Ultimately for now we just decided to recommend avoiding symlinks.
