### ISSUE TITLE
0.207.0 breaks multiple cursors

### ISSUE THREAD

**Issue by a-koka** [facebook/nuclide#1033]
### Expected Behavior
Cmd+Click should add multiple cursors

### Actual Behavior
Cmd+Click doesn't add multiple cursors

### Versions
* Atom: 1.14.3
* Nuclide: 0.207.0
* Client OS: macOS Sierra 10.12.3

**Comment by matthewwithanm** [comment]
Hey @a-koka! Sorry for the disruption 😔

This is actually expected behavior…we should probably post on the (very neglected) blog about it. The first time you cmd + clicked, you should've seen this notification:

<img width="422" alt="notification" src="https://cloud.githubusercontent.com/assets/126263/23384191/a8766e84-fcfe-11e6-8b57-2f25aad0536a.png" />

In short, Jump to Definition and Multiple Cursors both want to use it. In the past, we had some clever logic for determining which to do but, ultimately, the effect was just that it was never predictable. As of 0.207, cmd + click will always trigger Hyperclick. You can use cmd + option + click for multiple cursors or, if you really want to use cmd + click for it, change the Hyperclick trigger in the settings.

**Comment by a-koka** [comment]
Thanks for checking this out @matthewwithanm. I'm at a loss with how to change this setting. Would you be able to point me in the right direction please?

**Comment by matthewwithanm** [comment]
Sure! It's Under Nuclide's package settings:

Atom > Preferences > Packages > Nuclide > Settings > Hyperclick

<img width="548" alt="screen shot 2017-03-03 at 12 47 35 pm" src="https://cloud.githubusercontent.com/assets/126263/23568494/a4028e14-000f-11e7-9ca0-25535a0e1f58.png">

**Comment by a-koka** [comment]
Thank you!
