### ISSUE TITLE
Question: How to test `pkg/sample/*`

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/nuclide#1077]
Hi, sorry for making this a SO thread, but how do you test and fiddle with the sample packages you provide as examples? I tried replacing  the `sample` prefix with `nuclide`, but didn't seem to cut it. Thanks! Close as soon as you want!

**Comment by jgebhardt** [comment]
Hi @ev1stensberg, the `sample-*` packages are disabled by default.
You can enable them via Atom Settings > Packages > Nuclide > (scroll to the bottom) `Enable the "sample-*" feature`. Let us know if that doesn't work for you.

**Comment by ev1stensberg** [comment]
Thanks!

**Comment by ev1stensberg** [comment]
@jgebhardt Btw what is equivalent to https://atom.io/docs/api/v1.15.0/BufferedProcess in Nuclide? I found `safeSpawn` and combined it with `createProcesstream` and/or `ObserveProcesstream` but none seems to be working, except for the atom one.

**Comment by jgebhardt** [comment]
@ev1stensberg Check out Nuclide's `ObserveProcess` and all the various other abstractions around spawning processes: https://github.com/facebook/nuclide/blob/master/pkg/commons-node/process.js#L467-L472

**Comment by ev1stensberg** [comment]
@jgebhardt Done so, but still didn't seem to cut it :( I'll try to do some more experimenting. Is there any special convention you use for PR's? Such as using observables, providers etc..? I'm sending in a PR on adding CRA to Nuclide next week, it's pretty sweet. Allows beginners to avoid being in the terminal to get started with React, which I think is a major step in a direction that allows users to cut their learning curve down by a dozen in order to learn react.

**Comment by jgebhardt** [comment]
@ev1stensberg that sounds awesome. What exactly "doesn't cut it"?
Regarding conventions, it's hard to say without seeing what specifically you're doing, but a few things to keep in mind:
- Any calls to the file system, local processes etc have to be remoted using the Nuclide RPC framework (since Nuclide works transparently on both local and remote repos). This will already necessitate the use of the Atom Services API
- We highly prefer the re-use of existing abstractions & services (e.g. the diagnostics UI, quick-open, etc) over one-off UIs
- We loosely favor Observables over Promises for APIs, but it's not a hard-and-fast rule.

Do you have any rough drafts or outlines to share?

**Comment by ev1stensberg** [comment]
If I use your convention, the process doesn't start :( Could be an error on my side. I can open a WIP PR at the start of next week. Right now I've only hooked up a `homeFragment` command with an spawn, so there's really not much to see yet.
