### ISSUE TITLE
Folder Tree has stopped working

### ISSUE THREAD

**Issue by pjkarlik** [facebook/nuclide#1152]
### Issue and Steps to Reproduce
For some reason the top toolbar and folder view have stopped working. The toolbar on top just doesn't open or is viewable. The folder Tree opens as if it's a page and I am unable to see my files and folder/tree at the same time....

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom: v1.17.0
* Nuclide: 0.228.0
* Client OS: OSX 10.12.5
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by shushz** [comment]
I think these are various manifestations of Nuclide not yet being fully compatible with Atom 1.17.
The file-tree should be draggable to any place in the workspace, also I think there are some fixes to such problems in the upcoming release (probably today or tomorrow).

**Comment by crucialfelix** [comment]
You now have to drag the file tree into the sidebar. Drag it from the filename tab "File Tree" into the left edge. Look for the <  icon to appear. 

Same with diagnostics panel. But they aren't stable there, they will reappear in main when you reopen the project. Sometimes files are opened in the panel rather than the main area.  Doesn't work with splits very well.

**Comment by shushz** [comment]
So much has changed/was fixed in these months. I doubt it's still an issue.
