### ISSUE TITLE
Only nuclide-installer package on Windows7

### ISSUE THREAD

**Issue by matteotolazzi** [facebook/nuclide#118]
I installed the nuclide-installer package from the Atom package manager, restarted Atom and expected to see a list of "nuclide-*" packages but the only package installed was nuclide-installer.

**Comment by incon** [comment]
Is windows a supported platform for Nuclide?

**Comment by matteotolazzi** [comment]
I think so since Nuclide is installable through the Atom package manager and Windows is a supported platform for Atom.

**Comment by BlaM** [comment]
Same here. I installed nuclide-installer in Windows 8.1 and now I see a nulclide-installer package... But that's it. What am I supposed to do next? Do I need to install the other packages manually, too?

**Comment by nmn** [comment]
Please open up the command line and do
`apm search nuclide`

You will see a bunch of nuclide-packages. Install them with apm itself. Nuclide-installed and Atom's UI can take multiple days to do it all correctly.

Be mindful that certain packages are definitely not supported on Windows — Nuclide-flow won't work since Flow isn't supported on Windows.

I'm not sure about Hack and other packages. Without Flow however, you will get no autocomplete, typehints etc. So Nuclide is of little use on Windows. You may get Hack Remote development to work, perhaps.

**Comment by bolinfest** [comment]
In the most recent release of Nuclide, here is the line of code that installs each package:

https://github.com/facebook/nuclide/blob/master/pkg/nuclide/installer-base/lib/main.js#L212

Offhand, I would expect that to work on Windows, but that does involve shelling out to `apm`, so I guess that's not a guarantee?

**Comment by mostafaeweda** [comment]
`nuclide-installer` is gone now with the UP release: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
