### ISSUE TITLE
Where is the "start packager" command?

### ISSUE THREAD

**Issue by wellyshen** [facebook/nuclide#1392]
### Issue and Steps to Reproduce
1. Upgrade to 0.270.0
2. Press **SHIFT + CMD + P** to open command panel
3. I can't find `start packager` command of RN

### Expected Behavior
Show `start packager` command as usual

### Actual Behavior
I can't find `start packager` command of RN

### Versions
* Atom: 1.22.1
* Nuclide: 0.270.0
* Client OS: Mac OS 10.13.1

**Comment by wellyshen** [comment]
Should we use `metro: start` to instead of it?

**Comment by pelmers** [comment]
packager was renamed to metro at some point, try 'metro start' instead

**Comment by wellyshen** [comment]
@pelmers I tried `metro: start`. But nothing happened even then console log doesn't show up.

**Comment by pcattori** [comment]
Would be good to update the [docs here](https://nuclide.io/docs/platforms/react-native/#running-applications__react-native-packager) to reference Metro instead of React Native Packager.

Even with `Nuclide Metro: Start`, I also get no output in the console and can verify that a subsequent `react-native run-ios` creates its own bundler in another terminal tab, so its not that Metro is spinning up silently either.

**Comment by pcattori** [comment]
Seems like this is addressed in #1395
