### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: This socket is closed

### ISSUE THREAD

**Issue by vertexclique** [facebook/nuclide#1505]
### Issue and Steps to Reproduce
Compile test c code which is:

```
#include <stdio.h>
#include <unistd.h>
int main()
{
    int a = 1;
    while ( 1 > 0 )
    {
        sleep(2);
        printf ( "Hello World\n" );
        a ++;
    }
    return 0;
}

```

with `clang test.c -g -o testc`

and attach debugger from the pane.
I tried with both 7.4.0 and 7.9.0 node versions. Same error is happening. I think it is not from pty package.

### Expected Behavior
Debugger, should attach itself to the process.

### Actual Behavior
Getting error message below:

![screen shot 2018-04-23 at 17 27 19](https://user-images.githubusercontent.com/578559/39136638-029a1fe2-471c-11e8-93f3-c4f5b7cd3681.png)

### Versions
* Atom: 1.26.0
* Nuclide: 
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-ide-debugger-native-gdb@0.7.1
├── atom-ide-ui@0.11.0
├── nuclide@0.297.0
└── pretty-json@2.0.0

**Comment by pelmers** [comment]
What OS/gdb version are you using? cc @velocityboy

**Comment by ebluestein** [comment]
I'm not able to repro this with a recent Nuclide, since this issue is quite old I am going to go ahead and close it. Feel free to reopen if this is still happening.

**Comment by nbeAnomes** [comment]
Hello,
I know this issue is closed, but I exactly have the same problem. I am on macOS High Sierra (10.13.6), and I use atom 1.30.0.

additional details :
├── autocomplete-glsl@0.2.3
├── build@0.70.0
├── build-cmake@0.12.0
├── busy-signal@1.4.3
├── clang-format@1.30.0
├── file-icons@2.1.24
├── highlight-selected@0.14.0
├── language-babel@2.85.0
├── language-cmake@1.1.0
├── language-glsl@2.0.4
├── language-graphql@0.10.1
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── minimap@4.29.8
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── minimap-selection@4.5.0
├── nuclide@0.341.0
├── nuclide-format-js@0.0.47
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.8
