### ISSUE TITLE
Nuclide Devices tab in Atom stuck showing that an Emulator is running

### ISSUE THREAD

**Issue by csellis** [facebook/nuclide#1580]
### Issue and Steps to Reproduce
On the right hand side you see that the Android Emulator is still running. I had to cold boot of my computer while it was running an emulator. The emulator is no longer running but Nuclide thinks it is.
![screenshot from 2018-07-25 07-05-31](https://user-images.githubusercontent.com/814405/43197469-40a0350a-8fd9-11e8-8ed0-b1880f1d91a3.png)

### Expected Behavior
I expect it to check whether Android Emulator is actually running.

### Actual Behavior
Nuclide is not checking to see if Android Emulator is running and does not allow me to start it.

### Versions
* Atom: 1.24.0
* Electron: 1.6.16
* Chrome: 56.0.2924.87
* Node: 7.4.0
* Nuclide: 0.288.0
* Client OS: Ubuntu 16.04.4 LTS

**Comment by pelmers** [comment]
This nuclide version is quite old, are you running it as a workaround for #1576?
Otherwise I suggest updating Nuclide/atom and see if it still reproduces.

**Comment by aadsm** [comment]
I've familiar with this issue and it hasn't been fixed.
The problem here is that the devices panel checks for the lock file for each emulator and if it exists it assumes it's running. This is not a reliable assumption because the lock file will not be removed when the emulator is forced killed.
@csellis a quick workaround is to remove the lock file from `~/.android/avd/$DEVICE.avd/hardware-qemu.ini.lock`.

**Comment by csellis** [comment]
Update
I solved it by starting the emulator via Android Studio. Will look into
removing the lock file next time.
Thanks all.
