### ISSUE TITLE
diff-view does not work

### ISSUE THREAD

**Issue by cricalix** [facebook/nuclide#1602]
### Issue and Steps to Reproduce
1) Create a mercurial repository on local disk
2) Commit a file to it
3) Open Atom w/ nuclide
4) Add local folder, point at local repository
5) Change the file
6) In Uncommitted Changes, right-click the file, choose to open in diff view

### Expected Behavior
I expect a diff view tab to open, showing the original file on the left, and the changed file on the right.

### Actual Behavior
A diff view tab opens, with a title of diff-view?file=/path/to/fil&onlyDiff=true. There is no content in that tab, no errors in the log or console.

No change in behaviour (content, log, or console) is observed when Atom is switched to developer mode.

Loading the developer tools shows the pane has an active-item-path of atom:/nuclide/diff-view?file=...

Closing the tab triggers a "you're closing a file with changes, do you want to save?" dialog.

### Versions
* Atom: 1.2.9
* Nuclide: 0.339.0
* Client OS: Debian buster/sid
* Server OS (optional):
* Watchman: 4.9.4

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-python-virtualenv@1.0.2
├── file-icons@2.1.24
├── highlight-selected@0.14.0
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5 (disabled)
├── language-rust@0.4.12
├── language-scala@1.1.9 (disabled)
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.339.0
├── nuclide-format-js@0.0.47 (disabled)
├── python-black@0.3.0 (disabled)
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.7

**Comment by cricalix** [comment]
![image](https://user-images.githubusercontent.com/1478917/44832481-e1aee080-ac22-11e8-93dc-8ea4d839136e.png)

**Comment by sintylapse** [comment]
@aadisriram why is it closed? Is this issue fixed?

**Comment by amitkot** [comment]
@aadisriram I also get this behavior. Could you please explain why is this issue closed?

**Comment by dmitryame** [comment]
This simply does not work :( 
way to go -- just close it
Any updates?

**Comment by aadisriram** [comment]
I am extremely sorry about closing this without leaving an explanation.

The diff view is an fb internal only feature that at one point used to be open sourced. We had to do this because of how many fb specific features we were adding to it and over time the diff view wasn't providing enough value to external contributors and users. Unfortunately we weren't able to gate the context menu options to only show up in the internal build and this is one of those occurrences where the reference to diff view is externally shown. I'm sad to say this but the feature won't be open sourced :(
