### ISSUE TITLE
Flow sometimes requires multiple saves to pick up changes.

### ISSUE THREAD

**Issue by admmasters** [facebook/nuclide#191]
STR:
Save a js file in flow with a fixed issue, e.g. incorrect module path resolution.

Expected:
Flow issue disappears from the diagnostics UI.

Actual:
Flow issue persists until file is saved again. My workflow now involves saving a file twice. :-(

**Comment by nmote** [comment]
I've also experienced this happening sporadically since sometime late last week (around the time Flow v0.15.0 was released). My current theory is that we are hitting a race condition where Flow does not have updated results when we query it, but I haven't verified that theory.

In any case, it's high on my list of things to work on. I'll post updates here with progress. In the mean time, sorry for the inconvenience.

**Comment by ssorallen** [comment]
This seems to happen consistently for me. I've been hitting cmd-s a few times when I know the Flow annotations are outdated. Any luck tracking down what's happening here?

**Comment by nmote** [comment]
I've ruled out several potential causes but haven't yet figured out exactly what's going wrong.

**Comment by nmote** [comment]
It turns out that my initial hypothesis was correct, but I incorrectly ruled it out -- Flow hasn't picked up on the fact that the file has been saved by the time that we call it and ask for results.

The solution is either to figure out how to make sure that Flow wins the race, or re-architect so that there isn't a race at all. Long term I think we need to do the latter.

CC @gabelevi from the Flow team who I have been working with.

**Comment by nmote** [comment]
Unfortunately we had to revert the fix because it was mysteriously causing timeouts in our integration tests. We'll investigate and revisit.
