### ISSUE TITLE
nuclide-format-js doesn't support string extrapolation

### ISSUE THREAD

**Issue by vigneshm** [facebook/nuclide#208]
```javascript
var foo = `${myModule.getFoo()}-bar`;
```

doesn't add the following to the top

```javascript
var myModule = require('myModule');
```

**Comment by kyldvs** [comment]
Hmm, you sure? It works for me. I know TaggedTemplateLiterals aren't functioning now but it should search through the expressions of a template literal like normal and find the `myModule` expression.

**Comment by kyldvs** [comment]
This can be closed

**Comment by vigneshm** [comment]
I start with the following

```
/**
 * @flow
 */

var bar = require('bar');

function test() {
  console.log(foo());
  console.log(`${bar}-test`);
}
```

and when I do `format`, I get the following

```
/**
 * @flow
 */

var foo = require('foo');

function test() {
  console.log(foo());
  console.log(`${bar}-test`);
}
```

Format removed `var bar = require('bar')` and added `var foo = require('foo')`

**Comment by kyldvs** [comment]
Cool I see the issue. http://astexplorer.net/#/D3YrchZQyq

In `${bar}` `bar` is just an identifier, in general we don't classify a plain identifier on its own since it's almost always part of a larger expression, but in this case it's not. A fix will be to get all the identifiers from template expressions and include plain identifiers in the non-declaration-identifiers method.

**Comment by kyldvs** [comment]
Should literally be adding this here: https://github.com/facebook/nuclide/blob/master/pkg/nuclide/format-js-base/lib/utils/getNonDeclarationIdentifiers.js#L189

```
// `${bar}`
{
  searchTerms: [jscs.TemplateLiteral],
  getNodes: path => path.node.expressions,
},
```
