### ISSUE TITLE
Why the allGrammarScopes attribute?

### ISSUE THREAD

**Issue by steelbrain** [facebook/nuclide#218]
That attribute is (`allGrammarScopes`) is pretty much redundant, it could've been something like we have done in linter `grammerScopes: [*]`.
See this for example https://github.com/atom-community/linter/blob/d281da188bcb9fd8f0dc0cb7e9925e4e2ab08df3/lib/linter-registry.js#L54
cc @nmote @bolinfest @hansonw

**Comment by nmote** [comment]
- It's not documented on the [API Wiki](https://github.com/atom-community/linter/wiki/Linter-API). This is actually the first I've heard of this. I don't know if it's a recent feature, or if it has been around for a while, but I didn't know about it.
- I wanted something that I could implement in our [LinterAdapter](https://github.com/facebook/nuclide/blob/master/pkg/nuclide/diagnostics/store/lib/LinterAdapter.js) without interfering with the current linter API. Because this either did not exist at the time, or I just didn't know about it, we couldn't modify the functionality of existing properties and maintain compatibility.
- Generally I don't like mixing unrelated concepts. The `grammarScopes` array is an array of grammar scopes. Introducing a special value that can go in there but is not a grammar scope can become confusing. Even if the API is clear, it's easy to forget that there is a special value that you need to handle differently, and if you add to many such special values it will quickly become a mess. In contrast, it is immediately obvious that a separate property is something different, both to the consumer and producer of the API.

**Comment by steelbrain** [comment]
This has been around before the rewrite was published and Yep we should've documented it. I find it to be a cleaner approach than an attribute. and No we don't have too much special values, this is actually the only one. Everybody has a personal taste, and I respect yours :smiley:
