### ISSUE TITLE
why nuclide is so heavy weight?

### ISSUE THREAD

**Issue by cocodrino** [facebook/nuclide#239]
Hi, I'm checking my package folder and notice than every nuclide-* package is nearly 150mb of size...and they're a lot! 150 x ~12 = 1800 mb, that is much more than full ides like idea or netbeans!...

why is nuclide so heavy??..
thanks!

**Comment by nmote** [comment]
@scv119 has a better understanding of the installation process and may be able to provide more details, but from what I understand, our dependencies simply don't get deduped. So, we have a number of `nuclide-*` Atom packages, and each one depends on a lot of npm packages (for example, `nuclide-commons`). Because of the way packages get installed in Atom, each one of these packages pulls down its own copies of all of its transitive dependencies. This means that in essence, our `nuclide-commons` package and any other packages that are frequently-depended-on have a complete install for every `nuclide-*` apm package. This adds a lot of bloat and results in what you are seeing.

We need some way to avoid installing duplicate dependencies. @zertosh is looking in to options here, I believe.

So the good news is that this is a solvable problem, and not something inherent to Nuclide. The bad news is that we haven't solved it yet :disappointed:

**Comment by nmote** [comment]
Fixed by the unified package: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package
