### ISSUE TITLE
Running 'apm install nuclide-installer' installs v0.0.32 even though latest is v0.0.34

### ISSUE THREAD

**Issue by cmbrownfield** [facebook/nuclide#251]
I've blown away atom and reinstalled.  Run 'apm install nuclide-installer' and checked the version.  It was v0.0.32.

**Comment by nmote** [comment]
v0.0.32 is the latest version of our Atom packages. v0.0.34 was a release of only our npm packages, as described in the changelog.

**Comment by nmote** [comment]
For context: The reason we haven't done an Atom release in a while is because of issues like #239 -- basically, the number of packages we install doesn't work well with Atom's installation model, and it seriously damages performance. @zertosh is working on some massive changes to fix that, but in the mean time, since the number of packages is only increasing, and the ones we have are only getting larger, we don't want to do a release and cause even more performance problems.

I wanted to release npm packages because [flow-for-vscode](https://github.com/flowtype/flow-for-vscode) (which I just threw together with @bpasero) depends on nuclide-flow-base. I wanted to use a more up-to-date version of that.
