### ISSUE TITLE
[hyperclick] ability to change hover and click keybinding by keymap.

### ISSUE THREAD

**Issue by RB-Lab** [facebook/nuclide#273]
**Environment: Ubuntu; Atom (v1.2.1)**
**Package: Hyperclick (v0.0.35)**
**Provider: JS-Hyperclick (v1.4.1)**

Hello! First of all Hyperclick with JS-Hyperclick provider was that missing packages that finally convinced me to switch to atom from WebStorm. So it's great. However there is problem on Linux: hover & click behaviour is bound to `ctrl` key. The first problem is that in Readme it is said that in bound to `alt` key, so it makes me confused little bit. The second problem is that `ctrl+click` in atom is keybinding to place multiple cursors. So when you try to place multiple cursors on variables or functions editor jumps to it's definition instead of placing next cursor on the place you've clicked.
I finally replaced `event.ctrlKey` with `event.shiftKey` [here](https://github.com/facebook/nuclide/blob/master/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js#L294) (I can't use `altKey` because in Linux `alt+mousedown` is system keybinding for drag windows). But I'm pretty sure that not all will be satisfied with `shift+mousedown` keybinding. So the question is: is it possible to move it to keymap or to settings?

**Comment by durz** [comment]
I'm also using Hyperclick + JS-Hyperclick in Atom on Ubuntu. You're right that the ctrl key conflicts with the Atom keybinding for placing multiple cursors, and I agree that we need a way to configure the trigger key. Has anyone from hyperlick looked at this?

**Comment by matthewwithanm** [comment]
Thanks for the request! We're planning on implementing this, it's just a matter of time.

**Comment by nmai** [comment]
+1. Alt key is captured by the desktop manager for dragging windows, unfortunately. Would be nice to have options because I actually can't use hyperclick with the current keybindings :cry:

**Comment by jrial** [comment]
It's actually more than a nice to have feature request; it totally breaks multi-select under Linux.

See https://youtu.be/fZEN35UdJWw for a demonstration.

* The first part of the video shows a normal workflow involving multi-select with aotocomplete-python disabled.
* Then I enable the plugin, undo my changes, and try again
* And immediately, you see that self can not be double-selected by holding down CTRL when double-clicking the 2nd instance, as it will jump to its "definition" in the arguments list at the top of the method. I forgot to demonstrate that click-and-mark doesn't work either, but that's straightforward to verify as well.

Note: the video was shot against another plugin, autocomplete-python, but I later verified that the responsible plugin is this one. Didn't bother reshooting the video though.

**Comment by codeheroics** [comment]
I've tried using this package on Linux, but the ctrlKey binding is a problem. 

I think I understand the problem can't really be worked around without Atom implementing a way to handle mouse with keymaps (https://github.com/atom/atom/issues/2256 ?), but is there a way to at least implement a configuration key to disable clicks with the hyperclick package in order to only use the keyboard shortcut?

I tried adding a configuration key to the package, and it works if I only use hyperclick, but it seems incompatible with nuclide (it throws an error `"hyperclick" exported a "config"`).

**Comment by AWTrost** [comment]
this issue is also on mac osx (with the CMD key).  Same issue as @jrial.  Prevents me from using hyperclick, because it overrides the mutli select ability (cmd+double click multiple words and edit them simultaniously for example, not sure if multi select is the right terminology).  The atom core issue that @codeheroics mentioned is locked, and hasn't been updated in 10 months or so.  Is there no plan for this to ever be resolved either via nuclide or atom core(although nuclide team may not know)?

**Comment by mochacoder** [comment]
Running into the same issue as @AWTrost on a mac. To fix it I manually changed the following file to use the altKey instead:

~/.atom/packages/nuclide/pkg/hyperclick/lib/HyperclickForTextEditor.js:375
`return process.platform === 'darwin' ? event.altKey : event.ctrlKey;`

**Comment by olee** [comment]
Same problem for me but on windows (I think the platform does not really matter here it seems).
It would work without a problem in windows if it would actually use ALT key as the readme states.

**Comment by zaaack** [comment]
+1

**Comment by jacobmischka** [comment]
thanks for the patch, can the individual atom package be updated as well?

**Comment by jacobmischka** [comment]
Pinging @zertosh because I believe he's the maintainer of that package and I'm unable to file an issue there.

**Comment by zertosh** [comment]
@jacobmischka woops, sorry, I didn't realize issues were off. I made facebooknuclide/hyperclick#3. I'll try to do the sync now. The idea is to remove Hyperclick from Nuclide, and have the Hyperclick package be the source of truth.

**Comment by jacobmischka** [comment]
Thank you!

**Comment by zertosh** [comment]
Published as hyperclick@v0.0.39
