### ISSUE TITLE
Nuclide mercurial

### ISSUE THREAD

**Issue by ounos** [facebook/nuclide#275]
Gutter and file tree highlighting don't work at all and when I modify a file I get this error:
> Diff View Internal Error - Could not fetch common ancestor of head and revision: remote/master

Mercurial and watchman are installed and in my $PATH. Ubuntu 14.04.

**Comment by mostafaeweda** [comment]
Does your Mercurial repository have a branch `remote/master`?
If so, what's the result of running the command:
```
hg log --template {rev} --rev ancestor('remote/master', '.');
```
However, the 'remote/master' should be auto-detected in a better way rather than define it as a constant `FORK_BASE_BOOKMARK_NAME` in `HgServiceBase.js` because it could be different between repositories.

**Comment by Pradeek** [comment]
I'm facing the same issue. I don't have a branch named `master`, I have `default` instead.

**Comment by littlehaker** [comment]
Same issue, no `remote/master` but `default` branch

**Comment by mostafaeweda** [comment]
The only simple fix is to change the source to be 'default' instead of 'remore/master' until I handle that in a better way. Thanks for reporting.

**Comment by richarddewit** [comment]
`remote` and `master` are keywords from the Git universe. Mercurial uses `default` instead of `master`.

**Comment by mostafaeweda** [comment]
The commit here isn't a definitive fix for every use case, because every commit in Mercurial is a commit on the `default` (if you use bookmarks to stack your work instead of branches), but it will fix that error and the 'Diff View' would work fine, just not include multiple commits because the fork base is `default`.

Since different Mercurial projects have different origin `master` bookmarks, referring to the compare point of your work. To define a custom fork base, create a file `.arcconfig` in your project root with the contents:
```json
{
  "arc.feature.start.default": "$default_fork_base"
}
```

**Comment by zeffon** [comment]
I have default instead like @Pradeek.

`hg branch default`
