### ISSUE TITLE
[format-js-base][requires] incorrect formating with header comments

### ISSUE THREAD

**Issue by fabiomcosta** [facebook/nuclide#281]
When the first require is connected to the file's header comment, the requires are formatted incorrectly.
Example:

```js
/**
 * My module's header comment.
 * NOTE there is no blank line separating this comment from the following require.
 */
const x = require('x');
const a = require('a');
```

This gets formatted to:
```js
const a = require('a');
/**
 * My module's header comment
 */
const x = require('x');
```

Moving the comment to that spot is a good feature because it keeps the correspondent comments for each require line, but generally the first file comment refers to the whole file, so there could be an exception for this rule there.

**Comment by kyldvs** [comment]
Ah yeah. Handling comments is really hard. Right now if the comment is meant for the file I require there to be a new line separating it and the require. If it's directly above the require I assume it's attached to the require. For example there is no way to make these cases unambiguous:

```js
// Have to require these monkey patches for some reason.
require('monkey-patches');
require('a');
```

```js
// Copyright blah blah 2015
require('monkey-patches');
require('a');
```

In these two cases we want them to behave separately:

```js
require('a');
// Have to require these monkey patches for some reason.
require('monkey-patches');
```

```js
// Copyright blah blah 2015
require('a');
require('monkey-patches');
```

For now I expect this cases to be differentiated with a new line to get correct behavior:

```js
// Have to require these monkey patches for some reason.
require('monkey-patches');
require('a');
```

```js
// Copyright blah blah 2015

require('monkey-patches');
require('a');
```

**Comment by fabiomcosta** [comment]
Would it be possible to detect a pattern on the comment?
For example, if it's a multiline comment it has higher chance to be from the file than from the require.
```js
/**
 * High change to be from the file
 */
const a = require('a')
```
vs
```js
// probably from the require
const a = require('a')
```

**Comment by kyldvs** [comment]
Yeah it's possible to distinguish between Line and Block comments, or even test the value of the comment, but I don't really think it will solve the problem well enough. In my first example I think it would be reasonable if all of those were also block comments which would still cause things to be ambiguous.

In general I don't feel great about fixing an issue in a way that would allow another perfectly valid issue to be created that's basically the opposite of this one. If someone created an issue along the lines of "Comment on the first require doesn't follow the require when formatting" it would be perfectly valid after your proposed fix, and it wouldn't be fixable without breaking this again.

I like forcing the new line in between header comments and requires because it's unambiguous. And in general people naturally separate the header comment from the first line of code anyway.

**Comment by fabiomcosta** [comment]
Fair enough, we could force this empty line on our code with a lint rule and codemod the current files.
