### ISSUE TITLE
documentation issue? seems all setup to run a react native project, but I don't have the toolbars I noticed in the f8 nuclide keynote

### ISSUE THREAD

**Issue by bourkefloyd** [facebook/nuclide#31]
I'm not sure if not everything is available in the master branch, but when I open my react native project with the additional

  "nuclide": {
    "packageType": "Node",
    "testRunner": "npm"
  },

added to the package.json

I don't see the toolbars (select simulator, play, ...), or any options to get them to show up.
https://youtu.be/X0VH78ye4yY?t=1383

I know that the packages for nuclide are installed because I checked them in the atom installed packages pane.

My goal is to replicate the presentation to build and test react-native without xcode.

**Comment by josebalius** [comment]
Any eta when the react native packages will be landing?

**Comment by jacob-israel-turner** [comment]
+1 on ETA.  :)

**Comment by idibidiart** [comment]
+1 ETA please! :)

Bump

**Comment by rogchap** [comment]
:+1:

**Comment by crobinson** [comment]
what is +1 ETA  ??????????????

**Comment by Thorbenandresen** [comment]
+1

**Comment by tdugger** [comment]
total bummer.. So, the power Christian Legnitto showed off in March at the F8 conference, still hasn't made it to the masses?
@zertosh when you are done with unifying Nuclide in a single package.  Will the capabilities @LegNeato showed off in the F8 video be available?

**Comment by zertosh** [comment]
Hm, I just took a quick look at the video and a lot of functionality is already there - albeit, really poorly documented. We have some release issues (like how do we deal with a ton of pre-existing Nuclide packages) to sort out before we publish UP to the atom registry, but it's totally usable right now by cloning -> npm install -> apm link.

**Comment by tdugger** [comment]
Thanks for the reply @zertosh.  I did the clone -> npm install -> apm link and still don't see the build and simulator buttons at the top of the UI as shown at this point in the video (https://youtu.be/X0VH78ye4yY?t=1383).  Looking at my ~/.atom/packages directory, I then had the one link to the nuclide clone and then many other nuclide-* directories.  I then removed all of them except of the ~/.atom/packages/nuclide link and restarted atom.  Still no luck on the build and simulator buttons.  Clicking the Toggle Build Toolbar does nothing (besides moving the tabs down one pixel).

**Comment by zertosh** [comment]
Your build needs to be setup with [Buck](https://buckbuild.com/)

**Comment by tdugger** [comment]
@zertosh thanks.  I had not installed Buck.  I assume I also need watchman.

Since I don't have a project that uses Buck, do you know if the F8 app that @LegNeato used during the demo is available so I can test that my setup is correct?  Thanks.

**Comment by LegNeato** [comment]
I don't think so, looks like only the [old version](https://github.com/ParsePlatform/f8DeveloperConferenceApp) is available :disappointed:.

To check your setup you should be able to do the [buck quickstart](https://buckbuild.com/setup/quick_start.html) (for iOS, Android, or both) and it will create a working app that builds with Buck. Opening that directory with Nuclide should show the build toolbar and building from within Nuclide should work. Note that the quickstart isn't a RN app though.

**Comment by LegNeato** [comment]
I know the React Native support was being rewritten a bit ago to be more robust, which is why Facebook hasn't been pushing Nuclide + Buck as the default/best way to build React Native apps yet.

**Comment by tdugger** [comment]
Thanks for the reply Christian.  What will be the best way to build RN apps?  Am I running down a rabbit hole getting this setup?

**Comment by LegNeato** [comment]
It is my understanding that in the near future Buck+Nuclide will be the preferred (but not the only) way to build RN apps[1]. For now I would follow the generic RN directions, which means you'll have to juggle Xcode, Chrome, and an editor like Nuclide unfortunately (that is, no Buck integration).

Nuclide *does* provide a lot of value in this situation over a stock Atom or a Sublime or Xcode-only, as it has all the Flow/JS goodies (click to symbol, autocomplete, etc) and talks to clang to get the same goodies for ObjC.

The main thing it doesn't have is rebuilding native code automatically in Nuclide (as that requires Buck), which is why you'd need Xcode to press the build button or use `xcodebuild` from the CLI. When editing just JS, the default RN packager should see when you save JS code in Nuclide and reload the JS bundle in the app, so the JS "build" works today. Removing the need to run builds via Xcode or the packager via the CLI is the work that has been happening to make everything plug and play (for example, see https://github.com/facebook/buck/commit/60ccc96ee20640ba2c32cb16b22e8da694a6379f).

Nuclide even has a native debugger UI so that isn't needed in Xcode (ObjC) or Chrome (JS), though I am not sure it is turned on yet for everyone.

@mkonicek and @jamesgpearce may have more info or suggestions!

[1] Note: I left Facebook earlier this year so I don't know what is going on internally these days.

**Comment by LegNeato** [comment]
Looks like @davidaurelio and @natthu did most of the RN Buck stuff and may be able to add more color too.

**Comment by jacob-israel-turner** [comment]
@LegNeato Thanks for the info!  This is really helpful. :+1:

**Comment by rogchap** [comment]
Has anyone got an example BUCK file for building a react-native app? 
I have the basic BUCK setup for iOS, but because I'm not sure how to add the react-native (and others from npm) libraries with buck I get: `fatal error: 'RCTRootView.h' file not found`

**Comment by GianniCarlo** [comment]
I'm having the same issue as @rogchap , any pointers would be appreciated
