### ISSUE TITLE
File tree j/k navigation support?

### ISSUE THREAD

**Issue by chenglou** [facebook/nuclide#316]
The built-in file tree allows up and down through j and k.

**Comment by ssorallen** [comment]
We chose to leave VIM-style navigation out of Nuclide's file tree for the time being because there has been discussion of introducing alpha-style navigation, i.e. typing "j" would jump to the first entry starting with "j".

You can, however, add this yourself in your custom ~/.atom/keymap.cson. Create the file if it doesn't already exist, and add the following:

```cson
'.nuclide-file-tree':
  'j': 'core:move-down'
  'k': 'core:move-up'
```

**Comment by chenglou** [comment]
I see. What's the difference between alpha-style navigation and atom's built-in fuzzy/non-fuzzy file search?

**Comment by ssorallen** [comment]
> built-in fuzzy/non-fuzzy file search?

@chenglou Do you mean the modal that opens with `cmd-p`? The alpha nav I mean is when the tree-view/file-tree is focused, similar to when you open Finder on OS X, focus the tree, and type an alphanumeric character.

**Comment by chenglou** [comment]
I see, thanks!
