### ISSUE TITLE
Flow does not work in Remote Development mode

### ISSUE THREAD

**Issue by sometimesalready** [facebook/nuclide#343]
I have Flow version 0.20.1 installed locally and it works great when editing local files but in _Remote Development_ mode Flow seems does not work when editing remote files. I have installed flow on a remote machine as well but it does not help. Should Flow works in _Remote Development_ mode?

**Comment by ssorallen** [comment]
It should work for remote development. It's possible the Nuclide server is not able to find the `flow` binary.

@nmote How can @sometimesalready debug whether the server is able to find the Flow binary?

**Comment by nmote** [comment]
Just saw this -- unfortunately Nuclide is pretty silent if Flow is not found, since I didn't want to bother people who don't have any interest in using it. However, I think it would make more sense to first check for a `.flowconfig` and if it is there, throw up a warning if it cannot find Flow.

In the short term, all I can recommend is:

1. Make sure that `.flowconfig` exists at the root of your remote project, and that your files start with `/* @flow */`.
1. Make sure that `flow` is on your `PATH` on your remote machine. (try `which flow` or `flow version`).
1. If those don't work, see if there is anything interesting in your devtools console in Atom.

**Comment by nmote** [comment]
I've since improved a few things here. Now we pop up a warning if Nuclide can't locate the Flow binary, but we do locate a `.flowconfig` file. I also fixed a bug that could sometime prevent Flow errors from appearing from a remote connection.

**Comment by NikolayBorisov** [comment]
Still not working for me. One time blue pop up didn't help.

**Comment by nmote** [comment]
Is Flow installed on your remote server? The popup just tells you to install Flow, it doesn't install it for you.

**Comment by NikolayBorisov** [comment]
Yes, installed twice on server (Ubuntu 16.04)

> /home/nikolay/.npm_packages/bin/flow
> /var/www/project/node_modules/.bin/flow

and on local machine
```
$ which flow
/home/nikolay/.npm_packages/bin/flow
```

I tried set "Path to Flow Executable" to

> flow
> .bin/flow
> /home/nikolay/.npm_packages/bin/flow
> /var/www/project/node_modules/.bin/flow

And... 

> Flow was not found when attempting to start it in 'nuclide://[server_ip]/var/www/project'.

Btw, locally (macOS Sierra) everything works fine.

**Comment by nmote** [comment]
Unfortunately the "path to flow" setting only works locally. We've been meaning to figure out a scheme for per-server config (which is what it would take to do this right) but haven't.

I bet the path to `~.npm_packages/bin` isn't making it onto the `PATH` variable that the nuclide-server ends up with.

One thing that may help here is to enable the setting to allow Nuclide to use the project-local `flow-bin`.  Since you have flow-bin installed in your project folder that should work. Unfortunately we can't make this the default due to security concerns.

**Comment by NikolayBorisov** [comment]
```
$ echo $PATH
/home/nikolay/.npm_packages/bin:/home/nikolay/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/nikolay/.composer/vendor/bin
```
"Use the Flow binary included in each project's flow-bin" doesn't work too.
```
...
2016-09-17 00:00:10.304 DEBUG (pid:4508) nuclide - Registering interface AtomCommands...
2016-09-17 00:00:10.312 DEBUG (pid:4508) nuclide - Created new remote atom config at /tmp/.nuclide/command-server/9090 for port 37929 family IPv4
2016-09-17 00:00:14.085 INFO (pid:4508) nuclide - [unknown]: Flow server in /var/www/project
2016-09-17 00:00:14.095 INFO (pid:4508) nuclide - [not installed]: Flow server in /var/www/project
2016-09-17 00:06:39.461 DEBUG (pid:4508) nuclide - WebSocket connecting
...
```
Logs aren't useful enough

Flow perfectly works in terminal
```
nikolay at server in /var/www/project
$ ./node_modules/.bin/flow
index.js:7
  7: console.log(str;
                    ^ Unexpected token ;

...

Found 2 errors
```
or just
```
nikolay at server in /var/www/project
$ flow
```

**Comment by NikolayBorisov** [comment]
Woo-hoo! I fixed it!
Just did it:
`$ sudo ln -s /home/nikolay/.npm_packages/bin/flow /usr/bin`

**Comment by nmote** [comment]
Yeah, I'm guessing that the nuclide server wasn't picking up all the `PATH` changes in your `.bashrc`. I'm not sure about the specifics but I do know that it doesn't run quite like a normal shell.

**Comment by joshduck** [comment]
The Flow documentation suggests installing this as a local dev depencency: https://flowtype.org/docs/getting-started.html.

It would make sense to either amend the documentation for Flow or fix Nuclide so it can correctly find the binary.
