### ISSUE TITLE
Q: What's the goal of nuclide?

### ISSUE THREAD

**Issue by knowbody** [facebook/nuclide#35]
Do we want to have:
1. A pre-configured atom with useful packages and configuration (per se IDE), so a developer can download it and use out of the box? 
2. Or is it just for the sake of developing packages for atom?

In my opinion is the 1st option. If that is the case, should we take care of styling atom as well (so the editor is more readable)?

At the moment I use sublime for any React development, as it has the Oceanic Next theme, which is brilliant for:
- JSX 
- ES6  

This is what would make me switch to atom (nuclide) and do React dev there. At the moment there is a Oceanic Next for atom but it's far from the one in Sublime. I can imagine that good syntax highlighting would need to be done for PHP and other languages to have unified theme for everyone. By syntax highlighting I don't mean colors but the theme's syntax support for specific language.

I'd like to know others opinion on that

**Comment by bolinfest** [comment]
Now that Nuclide is public, hopefully resources like http://nuclide.io/ and https://code.facebook.com/posts/397706937084869 help clarify things, but if not, let me be clear:

* Nuclide is not a fork of Atom.
* Nuclide is a set of packages to add IDE-like functionality to Atom. In particular, we're focused on developing packages to support the technologies we use at Facebook, which includes (but is not limited to) React [Native], Hack, and Mercurial. We are committed to providing open source code that we use internally at Facebook to ensure it is of high quality and does not get stale.
* For technologies that we do not use at Facebook, we try to provide extension points that others can use for building packages for their own technologies. A prominent example of this is [`hyperclick`](https://atom.io/packages/hyperclick), as packages for other programming languages will likely also want to provide click-to-symbol functionality.
* If, over time, some of Nuclide's packages are merged into the core of Atom, that's great. If not, that's cool too, since we will continue to develop and make them available as a suite of packages. (We hope that [`hyperclick`](https://atom.io/packages/hyperclick) will be such a package, which is why it does not have the `nuclide-` prefix like our other packages do.)
* Currently, for end-users, we provide Nuclide via [`nuclide-installer`](https://atom.io/packages/nuclide-installer) because Atom does not currently support a way to declare Atom packages as dependencies of other Atom packages. If Atom ultimately supports the ability to install a suite of packages, we'll happily use that API.

**Comment by knowbody** [comment]
@bolinfest thanks for your answer. It wasn't very clear to me why would you put branding on it. Guessing it's a part of Facebook's OSS strategy. Thanks for sharing the tools though!
