### ISSUE TITLE
Flow: Error underlined at function definition when calling with arguments of wrong type

### ISSUE THREAD

**Issue by pristas-peter** [facebook/nuclide#356]
Shows when calling function with object, other types are displayed fine...
Underlined error should be on line 39, not on function definition line...

<img width="617" alt="atom-1" src="https://cloud.githubusercontent.com/assets/9489687/12848768/1a7b5996-cc1c-11e5-8fd5-33bb399f9c51.png">
<img width="508" alt="atom-2" src="https://cloud.githubusercontent.com/assets/9489687/12848769/1a7d133a-cc1c-11e5-9a67-87234645f45d.png">

**Comment by nmote** [comment]
Please reopen on the [Flow](https://github.com/facebook/flow) repository. We simply display the data they give us.

**Comment by pristas-peter** [comment]
I dont think its flow problem because the output in the box displays correct wrong line number

**Comment by nmote** [comment]
It is a Flow problem. I've had lots of discussions with them about error position issues. I'm not sure exactly what you're getting at when you say the "correct wrong line number" but I assume you're pointing out that line 39 is correctly displayed in the box? Flow can give us several different positions for a single error so that we can display the context in this box. However, there is no reasonable way for Nuclide to figure out which of the (in this case three) positions to actually put the error at. So, we just use the position associated with the first line.

The Flow team has taken responsibility for putting good positions on the first line of each error message. They have fixed this type of thing in the past. Hopefully that clears things up.

Oh, and your next question might be "If I run Flow from the command line, the correct position appears on the first line, so doesn't that mean it's a Nuclide problem?" That's because Flow displays errors differently in human-readable form and JSON form (which is what we consume). It's not quite as simple as changing the JSON output to match the human-readable output, since often the first line in the human-readable output is not actually the location you would expect. These things need to be handled by the Flow team on a case-by-case basis.

**Comment by pristas-peter** [comment]
Ok i understand your explanation, but there is nothing wrong with function definition, line 33. The error in the example  is On line 39, because I'm passing wrong value as function argument. When the wrong value is number, it's displayed correctly on line 38, if it is object with wrong type it's positioned on function definition. Regardless if I delete line 38 the output is the same... If the function is defined in other file, and you make call with wrong type, you dont even see that there is error.

**Comment by nmote** [comment]
Exactly -- I'm not disputing that it is an issue. I'm just explaining why it's an issue with Flow, not Nuclide.

**Comment by pristas-peter** [comment]
Ok I'll post this on flow. Thanks
