### ISSUE TITLE
Omnisearch doesnt show results

### ISSUE THREAD

**Issue by harshattray** [facebook/nuclide#357]
The omnisearch feature doesnt display any kind of results , it goes into a loading .. loop . 
![screen shot 2016-02-08 at 4 52 05 pm](https://cloud.githubusercontent.com/assets/3311805/12884446/5136698e-ce84-11e5-9b65-725d247aa307.png)

**Comment by ignlg** [comment]
Same here. Atom 1.5.0, OS X 10.9.5.

**Comment by viatsko** [comment]
Try
brew install watchman

And restart Nuclide.

**Comment by rawkode** [comment]
Experiencing this problem too.

Atom 1.5.3 - Linux (64Bit)

```
$ apm --version                                                                                                                                                                                 17:11:21 
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1
```

**Comment by antonbasic** [comment]
Had the same problem. Solved with suggestion from @viatsko 
Atom 1.5.3
OS X 10.11.3

**Comment by wmertens** [comment]
@viatsko thanks, that was it!

https://facebook.github.io/watchman/docs/install.html

Personally, I use http://nixos.org/nix so I had to symlink my local watchman binary to `/usr/local/bin` so that Nuclide would see it.

I think the proper resolution for this issue is that watchman is packaged with nuclide, presumably via an npm package…
