### ISSUE TITLE
Starting React Native packager in subdirectory

### ISSUE THREAD

**Issue by micksabox** [facebook/nuclide#378]
### Issue and Steps to Reproduce
Open an Atom folder, with a react native project in a subdirectory.
Execute 'Nuclide React Native: Start Packager' command

### Expected Behavior
Packager should start.

### Actual Behavior

<img width="438" alt="screen shot 2016-02-26 at 3 30 24 pm" src="https://cloud.githubusercontent.com/assets/2997810/13364628/df6f5d9c-dc9d-11e5-87be-1e8db576257d.png">

### Versions
* Atom: 1.5.3
* Nuclide: 0.119.0
* Client OS: Mac OS X 10.10.5
* Server OS (optional):

### Additional Details
- My react native project subfolder has a react native dependency in package.json
- When I open the subfolder with Atom, the packager works, but since I have shared server code it makes sense to open the parent directory instead

**Comment by matthewwithanm** [comment]
Hm, this is currently the expected behavior. (If you want another directory open, you can add both to the project.)

I'm honestly not sure about recursively searching the tree for packager information. Not only is it potentially costly, it also means we'd have to account for the possibility of finding multiple RN projects. I think a better idea might be to specify the packager command in a config file in your top directory. As the error message alludes, this can already be done with a `.buckconfig` file that looks like this:

```
[react-native]
    server = path/to/node_modules/react-native/packager/packager.sh
```

In the future, I think we'll probably be adding other ways to configure this command (e.g. [a package.json script][0] or some kind of Nuclide-specific config) but that's still a bit up-in-the-air 😥.

[0]: https://docs.npmjs.com/misc/scripts

**Comment by micksabox** [comment]
Gotcha, thanks. I agree with you. Although the error message makes it seem like this is possible, which is why I opened this issue. I'll close it for now.
