### ISSUE TITLE
Remote files tabs are not here when VCS Coloring of tabs is enabled

### ISSUE THREAD

**Issue by alanzanattadev** [facebook/nuclide#420]
### Issue and Steps to Reproduce
Tabs of remote files are not present when VCS Coloring of tabs is enabled.

Steps to reproduce  : 
  - Connect to a remote folder
  - Enable VCS Coloring of tabs in tabs settings
  - Open a remote file
  - Look at the tabs, it's missing

### Expected Behavior
Tabs should be presents for remote files

### Actual Behavior
Tabs aren't here

### Versions
* Atom: 1.6.0
* Nuclide: 0.125.0
* Client OS: Ubuntu
* Server OS (optional): MacOSX El Capitan

**Comment by mostafaeweda** [comment]
@alanzanattadev that's because this option calls a sync method: `getRealPathSync` which can't be supported on remote directories (because any remote operation is `async`).

We hope Atom will move away from using any of those synchronous APIs, so we and other third party developers can be more compatible no matter what we try to achieve.

As this is non-actionable for us at the moment, I'll close and please avoid that option when developing on Nuclide.
