### ISSUE TITLE
Documentation: Nuclide / Mercurial / Watchman minimum version requirements

### ISSUE THREAD

**Issue by DavidPesta** [facebook/nuclide#432]
I have attempted the following on both Lubuntu 14.04 and also Xubuntu 14.04 with the same results.

There is a bounty on StackOverflow for this issue that expires in a week if anyone is interested:
http://stackoverflow.com/questions/36222286/mercurial-support-partially-not-working-in-atom-nuclide

I have installed the latest version of watchman, which can be found here:

    /usr/local/bin/watchman

This is a fresh new install of Atom and Nuclide with the latest version of everything.

I performed the Install Recommended Packages on Startup and I watched them install after restarting.

I have a test project with files added to the Mercurial repository. The repository .hg directory sits at the root of the project. When I open a Diff View into a file, Nuclide picks up the previous Mercurial version of that file just fine as I make edits and it shows the comparison between the two. Previous version on the left is shown. So I know that Atom-Nuclide is able to interact with the Mercurial repository.

However, nothing else seems to be working for Mercurial support.

1. When I select "Toggle Blame" on the same file where Diff View is working, I get this message: "Failed to fetch blame to display. The file is empty or untracked or the repository cannot be reached."

2. The File Tree Highlighting does not work. No colors on any of the files in any of their mercurial states.

3. The colored Line Modification Notifications do not show inside of the Atom gutter.

4. The Added and Removed Lines feature is not showing in the status bar.

I am looking forward to trying out Mercurial and Atom-Nuclide with these features. Thank you in advance for your help.

**Comment by get-trucked** [comment]
@DavidPesta  Are you able to let us know some more debugging info.

what version of mercurial are you running. `hg --version ` will tell you.

Also do you have any errors in the dev console in atom, `Ctrl + Shift  + i`

**Comment by nene** [comment]
I ran into this same issue with first-time install of Nuclide.

Turned out I was using Mercurial 3.0.1. Upgraded to 3.7.3. This solved the issue with "Toggle Blame" crashing. But the highlighting of modifications still didn't seem to work.

Then discovered that I also need to install `watchman`. Only found it out through the author of this issue mentioning it. The instructions for installing it are almost hidden at the end of the [Setup guide.](http://nuclide.io/docs/editor/setup/)

So installed watchman 4.4.0 and initially things still didn't seem to work... then finally I realized that I have to wait a bit for watchman to notice the change and update the file tree highlighting. Takes like 5 seconds on my repository.

I thought that maybe I can speed things up by defining a "Working Set", but apparently this feature has stopped working. It worked before, but now with updated Mercurial and Watchman it no more does. Attempting to create "Working Set" results in the following error in dev console:

    /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:1015
    Error setting item in array: Validation failed at nuclide.nuclide-working-sets.workingSets, "[object Object]" must be an object

Tried to speed things up by adding a smaller subset of repository as the project folder. But things remained about the same... still a lag of several seconds between saving the file and highlight appearing in file tree.

Oh well... at least it works...

But now the file tree highlighting no more works with Git. Disabling Nuclide makes Git projects work properly again.

**Comment by get-trucked** [comment]
It would be nice if the pre reqs were a little more specific, would it be possible to update the docs?

It appears for Nuclide to work properly it requires a specific mercurial version with an experimental api call `hg status -T` to be specific.

On a side note, this may catch out quite a few ubuntu 14.04 lts users as the ubuntu repo is way out of date with mercurial.

**Comment by mostafaeweda** [comment]
The git file tree highlighting is coming pretty soon (actively working on it and turned out to be super easy).
It needs Atom >= `1.6.x`

**Comment by get-trucked** [comment]
That is really good news that git highlighting will be added soon. But I dont think that was quite the point of the issue.

The readme for the hg repo package here https://github.com/facebook/nuclide/tree/master/pkg/nuclide-hg-repository has the recommended version for mercurial being 3.4

Could this be placed in the requirements shown on the nuclide install page here http://nuclide.io/docs/editor/setup/#linux__prerequisites

**Comment by JoelMarcey** [comment]
Will require us to update Nuclide Mercurial prerequisites in the docs to show how to get full support
