### ISSUE TITLE
Git ignored files stubbornly hidden in file tree

### ISSUE THREAD

**Issue by rulatir** [facebook/nuclide#491]
### Issue and Steps to Reproduce

I clear **every** configuration option I can find that could possibly cause hiding gitignored files/folders in the tree view. In particular, ["nuclide-file-tree"].hideIgnoredNames is set to false.
### Expected Behavior

Gitignored files and folders should not be hidden in the tree view.
### Actual Behavior

Gitignored files and folders are hidden in the tree view.
### Versions
- Atom: 1.6.0
- Nuclide: 0.135.0
- Client OS: Linux
### Additional Details
- Installed packages (`apm ls --installed`):

```
├── ctrl-last-tab@0.3.0
├── git-time-machine@1.5.2
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.20.8
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── nuclide@0.127.0
├── sort-lines@0.14.0
├── symbols-tree-view@0.12.0
└── tool-bar@0.4.0
```

**Comment by shushz** [comment]
The hideIgnoredNames setting controls whether to hide or not files that match the configured ignore pattern.
What about the "Exclude VCS Ignored Paths" setting in core Atom's settings? Is it unchecked?
Also, the installed packages above lists Nuclide at version 0.127, not 0.135. Could you verify, please, that you're on a recent version?

**Comment by brad-decker** [comment]
i would like VCS hidden files to not be considered for things like Omni serach/full text search but i don't want them to be hidden from the sidebar. How would i go about doing that in settings?

**Comment by diego-vieira** [comment]
@shushz the setting is "Hide VCS Ignored Files" and it's located at Atom Tree View package which is disabled by nuclide in favor of nuclide's own tree view.

**Comment by diego-vieira** [comment]
Instead of hide the files, I think it should fade the files ignored and not index. I couldn't find where this is set, I would be happy to send  a PR.

Below is two images comparing both packages. As you can see the *node_modules* is ignored, but it's still there.

**Atom Tree View**
![screen shot 2016-05-12 at 22 45 18](https://cloud.githubusercontent.com/assets/930792/15235626/5b807386-1893-11e6-8992-946efba65201.jpg)

**Nuclide File Tree**
![screen shot 2016-05-12 at 22 45 27](https://cloud.githubusercontent.com/assets/930792/15235627/5b8417ca-1893-11e6-9f4c-0eb1e6bd4911.jpg)

**Comment by shushz** [comment]
@diego-vieira  I was talking about the setting called "Exclude VCS Ignored Paths" from Atom's Core Settings. If you uncheck it, the gitignorred files show up faded, just as in Atom's tree-view.
![screen shot 2016-05-13 at 9 32 57 am](https://cloud.githubusercontent.com/assets/8860623/15254920/06898254-18ee-11e6-8c6d-d164f6d6de23.png)

**Comment by diego-vieira** [comment]
@shushz ah, great, yeah they are back now on file tree after unchecking, although it's not greyed out for me on v0.136.0.
.git, .idea and node_modules are ignored in .gitignore.

Thanks

![screen shot 2016-05-13 at 13 58 38](https://cloud.githubusercontent.com/assets/930792/15255532/dd3cee7a-1912-11e6-9f67-0c312eba0054.jpg)

**Comment by ExpHP** [comment]
Huh, I could have sworn that I was completely unable to get it working a couple of days ago, but *trying it again today I am successful;* I now see **visible, grayed out entries** for .git and files in .gitignore in the Nuclide file tree.  Here is a messy project in the middle of migration:

<img src="http://i.imgur.com/8wFtwxR.png">

Here's [my config.cson](https://gist.github.com/ExpHP/2106cd1b3d2536add1e839e6e49417ae) for other lost souls to compare against.

**An aside:** Playing around with the settings, I observe that the two configuration options discussed above each have the effect of hiding files (in the sense of being removed entirely from the file list), but by **two completely orthogonal criteria**:

* Setting `core["excludeVcsIgnoredPaths"]` hides exactly those files which are grayed-out. (.git plus those in .gitignore)
* Setting `nuclide["nuclide-file-tree"]["hideIgnoredNames"]` hides exactly those files which match `core["ignoredNames"]`. (in this image, those are .git and src/.draw.ts.swp)

It is nice that these work orthogonally to each other, as I find the second option desirable.

**Comment by rasenplanscher** [comment]
I ran into this myself: as it stands (`nuclide@0.202.0`), I am really missing the `Hide VCS Ignored Files` setting from `tree-view` in `nuclide-file-tree`. I have enabled `Exclude VCS Ignored Paths` in Core in order to not have fuzzy finder give me ignored files, but I still want to see them in the file tree. Those two are related but distinct settings.

**Comment by maoueh** [comment]
Completely agree with @rasenplanscher, unchecking `Exclude VCS Ignored Paths` is not a viable solution. The main reason is that by unchecking the option, the fuzzy-finder will now look into excluded folders when doing searches which is undesirable.

Another option `Hide VCS Ignored Files` would be needed I think, or something else so that VCS excluded files are still displayed in the file tree.

**Comment by NameFILIP** [comment]
Please, add the `Hide VCS Ignored Files` back to the config. Once in a while, I like to dive into the `node_modules` folder and see the source of the modules. As other people said, I want to see ignored files in the tree, but don't want fuzzy search to look there. It used to work like this before.

**Comment by souporserious** [comment]
+1

Not sure why there isn't an option for this 😕 is there any way to force it until this gets fixed? Really annoying when needing to dive into hidden files.

**Comment by pinkstrings** [comment]
+1

This would be super helpful.

**Comment by patotoma** [comment]
+1 it really is annoying

**Comment by unordered** [comment]
+1

**Comment by JonnyPickard** [comment]
+1 Super annoying having such a good tree interface that hides files.

**Comment by KingScooty** [comment]
+1

**Comment by dfosco** [comment]
+1

**Comment by blakek** [comment]
One difference I've found is that you can toggle VCS ignored files in `tree-view` by pressing `i` (default keybinding) when the tree view has focus.  However, the only way I've seen to toggle visibility with `nuclide-file-tree` is to toggle the Atom core setting.

`nuclide-file-tree` intercepts the keystroke and fires the `go-to-letter-i` action, even with the "Enable prefix-based keyboard navigation" option disabled.

**Comment by SavePointSam** [comment]
Thank you @xixixao!! 🎉
