### ISSUE TITLE
Outline view does not show tests if uses `.only` with describe or it.

### ISSUE THREAD

**Issue by bsr203** [facebook/nuclide#546]
### Issue and Steps to Reproduce
For mocha based tests, It outlines tests with `describe` and `it`, but hides  `describe.only` and `it.only`

### Expected Behavior
It should display tests running with only.

### Versions
* Atom: 1.8.0
* Nuclide: 0.141.0
* Client OS: Mac OSX

**Comment by nmote** [comment]
I'm not sure how far down this path I want to go, but matching against a few more strings is relatively low-effort. I'll implement this.

**Comment by bsr203** [comment]
thanks. In addition to the common ones, if a list of string or a regexp can be configured through the UI, that may help on maintainability. IS that possible?

**Comment by nmote** [comment]
Well, it's actually more complicated than just "adding something to a list" because `describe.only` is actually a different AST node than just `describe`, due to the dot: http://astexplorer.net/#/KFqGXzZ4TW

So, I'm worried that making it configurable would actually just cause more confusion because of issues like this.

Honestly when I wrote this I just wanted something quick that would help me out with the tests I write... I was worried about the inevitable feature-creep involved in adding something like this that's not actually spec'd as part of the language. And here we are 😛.

**Comment by bsr203** [comment]
thanks for the quick response. I was using taglist before (similar to the one with vim) and what is available now in nuclide is way better. I would say this is THE best  feature for me as changing syntax of javascript ( ES6 , ES6, flow,..) makes the file longer and harder to navigate. outline really help. I could live without the above requested feature, as you typically uses `only` with one test, which typically you are currently working on. Typically people may remove `only` after they done with it. So, you are free to close this and we may only have a minor annoyance. I may also prioritize https://github.com/facebook/nuclide/issues/437 and similar. thanks for your great work and support. cheers.

**Comment by nmote** [comment]
I'm glad you like it! I'm slowly chipping away at these feature requests when I have a few minutes here and there. I did this one first (change is currently in review) just because it's pretty quick. But I'd like to point out that it's not very hard to add things like #437 and I'll happily review pull requests (e.g. #441). If you have a new request it's worth opening an issue first to make sure we agree it would be good to have. But for an existing issue feel free to put something together if you want it urgently.
