### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by milesj** [facebook/nuclide#56]
This is my setup:

Windows 7
Python 2.7.2 installed to C:\Python27
Node.js 0.12.4 and NPM 2.10.1 installed via the Windows installer
Atom 0.208.0 and APM 0.171.0 installed via the Windows installer

I keep receiving the following errors when executing the `scripts\dev\setup` file. I'm also running this as an administration through the command prompt.

```
START INSTALL: 2015-06-10 19:53:21.311000
Installing dependencies for Node package nuclide-node-transpiler...
Traceback (most recent call last):
  File "scripts\dev\setup", line 44, in <module>
    package_manager.install_dependencies(npm, include_packages_that_depend_on_atom=include_apm)
  File "scripts\dev\../lib\package_manager.py", line 47, in install_dependencies
    installer.install()
  File "scripts\dev\../lib\package_manager.py", line 151, in install
    self._do_serial_install()
  File "scripts\dev\../lib\package_manager.py", line 157, in _do_serial_install
    install_dependencies(config, self._npm)
  File "scripts\dev\../lib\package_manager.py", line 315, in install_dependencies
    npm.install(package_config['packageRootAbsolutePath'], local_packages=package_config['localDependencies'], include_dev_dependencies=package_config['includeDevDependencies'])
  File "scripts\dev\../lib\npm.py", line 49, in install
    self._npm_install(package_root, include_dev_dependencies)
  File "scripts\dev\../lib\npm.py", line 55, in _npm_install
    self._execute(npm_command, cwd=package_root)
  File "scripts\dev\../lib\npm.py", line 85, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=devnull)
  File "scripts\dev\../lib\fs.py", line 91, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
```

My projects are installed to a separate drive, the E: drive, so I'm curious if that's an issue in itself.

I've also tried this patch found in another issue, no go. https://github.com/apuckey/nuclide/commit/f33bdcef41125de52724e36a224f0f2688d03124

Any help would be appreciated.

**Comment by bolinfest** [comment]
@milesj Yes! I moved our test runner (that depends on `jasmine-focused`, which depends on `git+https://github.com/kevinsawicki/jasmine-node.git#81af4f953a2b7dfb5bde8331c05362a4b464c5ef`) into a new `nuclide-jasmine` package, which is now listed under `devDependencies` in all of our `package.json` files as of https://github.com/facebook/nuclide/commit/33ffc40e2d8178f921d4a5319ba70133d659a474.

If you use `npm install --production`, it will not try to install `devDependencies`. This is good for end-users because `apm install` calls `npm install --production`. However, we assume that developers are trying to *develop*, so we don't want to exclude `devDependencies` when `npm install` is called from `./scripts/dev/setup`.

So I'm not sure if this fixes things for you in the developer case, but it will fix things for users who install the prebuilt packages via Atom and do not have Git on their `$PATH`.
