### ISSUE TITLE
Nuclide start up time

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/nuclide#674]
I recently started using flow and saw that the flow docs recommended to be used with nuclide for getting type errors and annotations as you develop. So I started using it for a week or so. I thought Nuclide was broken because I would never get type annotations when I hover over an variable or would never get in line flow errors being pointed out. I forgot to uninstall nuclide and today after working for about 2 hours straight I just start to get the annotations and error highlighting of types. So its awesome that it isn't broken but kinda sucks that it took so long for it to start providing feedback and highlighting of errors, etc. Don't know if this is a known issue but I just wanted to report it.

### Versions
* Atom: 1.9.9
* Nuclide: 0.163.0
* Client OS: Mac OSX

**Comment by zertosh** [comment]
Flow reporting should be pretty instant. There was a bug in Atom 1.9.0-1.9.7, that was fixed in [Atom 1.9.8](https://github.com/atom/atom/releases/tag/v1.9.8), where features that wait on specific grammars (flow waits for `language-babel` or `language-javascript`), weren't getting activated until you opened a new of that type. So if you opened Atom, and the js file you were working on was already open, flow would never see it until you opened a new js file.

I noticed that you're using 1.9.9 now, but maybe you were using an Atom with the bug then? Is your 2 hour wait consistently reproducible?

**Comment by kennetpostigo** [comment]
@zertosh well yea I've had nuclide installed for a few days which is why I forgot to uninstall it because every time I opened atom it would never show anything. Till today where it started working all of a sudden.

**Comment by zertosh** [comment]
@kennetpostigo so to be clear, if you quit Atom, and open it again, flow doesn't work until after a few hours?

**Comment by kennetpostigo** [comment]
@zertosh yea, thats the case for me with nuclide. Maybe I should reinstall atom?

**Comment by zertosh** [comment]
I can't imagine a problem with Nuclide or Atom that would cause that issue :/

**Comment by kennetpostigo** [comment]
@zertosh So I just reinstalled atom along with nuclide. It seems to be working now when I open up a new file all the annotations and auto completion stuff work.

**Comment by zertosh** [comment]
Strange. Glad it's working though.
