### ISSUE TITLE
Proposal: split Nuclide in small, reusable & hackable modules

### ISSUE THREAD

**Issue by yamsellem** [facebook/nuclide#710]
I know Nuclide comes for a great will of empowering development, but, if it starts offering small reusable, hackable, interoperable blocks, it will have a way better impact.

Some example here:
- diff view is great, but only works for mercurial and no one from the community has hacked this to offer it with git. Seems odd, the diff view is great, and git is largely used
- test runners are a great initiative, but their still ain't any mocha runner
- debugger is a great ressource too — the dots in the margin are great, the integration with chrome debugger too—, but seems to not work in here
- in general everything miss a starter guide, like, how to add a test runner, how to start debugging a webapp, how to integrate flow, etc

Installing a javascript test runner or debugger has nothing to do with stuff related to Hack, Working Sets, Mercurial or other. Embracing Atom openness, small modules, community driven approach, keeping the hackable spirit, will help being improved by others, even amazed by what they can do with your stuff — like all the things Nuclide try to bring to Atom should impress Atom creators.

I don't say that Nuclide should stop being a bundle, what I suggest is that it would be way better if it becomes a lot of small parts, hacked by the community. Which can be used individually.

Thanks for your open mind 'bout this.
Take care.

ps. it seems that there's a [(modest) start here](https://atom.io/users/facebooknuclide)

**Comment by bolinfest** [comment]
Originally, Nuclide was implemented and distributed this way, but due to some details of how the Node/Atom ecosystem work, this was unsustainable: https://github.com/atom/atom/issues/8217. This caused issues such as https://github.com/facebook/nuclide/issues/203.

The reality is that we can move a lot faster and deliver a better overall experience by developing in a monolithic repository and releasing as a single package.

If you go to Nuclide's settings, you can disable individual features that would normally be their own Atom packages if there were a reasonable way to distribute them as such.

**Comment by nmote** [comment]
Like @bolinfest says we did this, and really wanted to fully embrace the modular philosophy of the Atom ecosystem but it was unsustainable. Our focus has to be on making sure that Nuclide works well as a whole, and when it was 100 different packages it simply didn't. In fact, because each Nuclide package shared so many dependencies that weren't deduped, the single `nuclide` package we have now is not much bigger on disk than *each* package we had in the past.

It sounds like you're specifically after extensibility, right? Most of the things you mention actually *are* extensible via Atom's service-hub. We'd like to make our APIs more stable and well-documented but nobody's found the time yet.

So today you actually can write a separate Atom package that interfaces with Nuclide. The main hurdle is finding and understanding the APIs. Hyperclick, diagnostics, type coverage, outline view, code formatting, to name a few, will all happily consume data from other packages.

There are a few main issues we are currently facing, but none of them are intractable:
* We don't have good documentation of our APIs.
* Many of our APIs should not be considered stable. We should make it clear which ones are and commit to not making breaking changes without a grace period.
* Some features don't actually use service-hub. For example, I'm pretty sure that getting diff view working with Git would require nontrivial changes to the Nuclide codebase itself. In this particular instance I'm not sure that's a bad thing but there may be some features worth revisiting.

So, if you'd like to pitch in I think the main thing that would help right now is documentation. You can take a look at all the packages in `pkg`, find out which ones expose functionality via service-hub by looking in `package.json` files, and then submit documentation PRs to the `docs` folder. It's probably worth opening an issue first so we can discuss whether we want to consider a particular API stable.

I'm closing since we aren't going to split Nuclide up into a ton of small packages (with the possible exception of a few parts like hyperclick). But we do share your goals regarding extensibility.

**Comment by bernatfortet** [comment]
@bolinfest I was wondering about disabling specific features. I don't see this option.

I love the working sets feature in Nuclide. It's awesome! And I'd like to use it for projects where I don't need all the functionality of Nuclide.

How can I use only The working sets module?

Thanks

**Comment by nmote** [comment]
@bernatfortet Right now it's unfortunately a bit hidden (this isn't a deliberate choice, just nobody's gotten around to making it better yet). You have to go to the settings for the "nuclide" package and then scroll all the way down. You'll see a list of checkboxes about various features there.

**Comment by yamsellem** [comment]
I've just installed Nuclide again, and the question is bothering me again; for now, I just want the debugger, nothing else (maybe latter, but the omnisearch for example bothers me and it seems it cannot be disabled, or I already have another linter, things like that).

If you cannot consider releasing the nuclide debugger as a standalone atom package, can you please envision a way to easily disable every nuclide feature and only activate them one by one? It will be like enabling hell's power but an inch after an inch, instead of having all (if not all, a lot of it) or nothing?

Thanks again.

**Comment by nmote** [comment]
Like I said in my last comment, you actually can disable individual pieces of Nuclide and leave only the ones you want running. You can certainly disable everything but the debugger pieces if that's what you want.

**Comment by yamsellem** [comment]
@nmote Ah, ok, there is a `Use` menu in the settings that offers to disable every feature one by one.

May you consider renaming this `Use` settings in `Activate / Deactivate Nuclide features`?

May you consider adding a `disable all` button, so anyone can start using Nuclide little by little? Disable every 94 (!) features take me a minute (_and I code on several computer, has you may think_).

May you consider adding a long description to every feature plus a hyperlink to the documentation (_or the repository, if any_)?

The settings panel is not very straightforward and easy to use IMO; it seems to be design as a `configure what's in there by their technical name` more than a `choose and configure Nuclide features`. Improving this settings pane would greatly help me in the use of Nuclide and the progressive activation of its features.

May you consider reordering those features, so instead of a disable button in a given menu, every feature would be described, would list every options they gives, and offers a disable button (_like the Mercurial Diff Grammar, for example — which lack of context and a disable button, yes — but displays all its options in one place_)?

Thanks a lot.

**Comment by yamsellem** [comment]
@nmote If I enable only `nuclide-debugger`, `nuclide-debugger-node` and disable every other features, the debugger won't show anymore. Can you help me on this too?
