### ISSUE TITLE
"Add Project Folder" does nothing

### ISSUE THREAD

**Issue by jesseschalken** [facebook/nuclide#843]
### Issue and Steps to Reproduce

![screen shot 2016-10-27 at 6 20 44 pm](https://cloud.githubusercontent.com/assets/1559204/19758083/45832e80-9c72-11e6-858c-91db7f0bf372.png)
- Click "Add Project Folder" in the tree view.
- Select a folder.
### Expected Behavior

The selected folder appears in the tree view.
### Actual Behavior

Nothing.

There is nothing in the Nuclide console and the Developer Tools console shows no errors.
### Versions
- Atom: 1.11.2
- Nuclide: 0.177.0
- Client OS: macOS Sierra 10.12
- Server OS (optional): n/a
### Additional Details
- Installed packages (`apm ls --installed`):

```
Community Packages (1) /Users/jesseschalken/.atom/packages
└── nuclide@0.177.0

└── (empty)
```

**Comment by shushz** [comment]
That's a very weird thing. We use this functionality daily and I've never seen any problems with it.
One thing I notice in your screenshot is that the "tool-bar" package appears not to be installed. This is not a problem by itself, but it it might indicate an incomplete install.

Could you try restarting Atom and see whether the problem persists?

**Comment by jesseschalken** [comment]
What's the relationship with the `tool-bar` package? It wasn't installed by default by installing `nuclide`.

Installing the `tool-bar` package manually doesn't help. Restarting Atom doesn't help. Reinstalling and deleting `~/.atom` and starting from scratch also didn't help.

**Comment by nmote** [comment]
I'm just as stumped. What if you open Atom and then use `atom -a folderToOpen` from the command line? You may have to run 'Install Shell Commands' from the Atom menu first, if you haven't done so already.

Regarding tool-bar -- automatic installation of recommended packages is off by default, so this setup is normal (https://nuclide.io/docs/editor/setup/#post-installation__recommended-packages). For context, we turn this on by default for Facebook employees so that's where the confusion came from.

**Comment by leeahoward** [comment]
I am having this problem. I am able to see all files if I rename the .git folder

**Comment by shushz** [comment]
@leeahoward Could it be that all of your project files are `.gitignore`d? You can try unchecking the "Exclude VCS Iignored Paths" in Atom's core settings and see whether it helps.

**Comment by leeahoward** [comment]
I did try removing/renaming the .gitignore file first, but it didn't help.
Gitignore is not excluding everything.
I did disable "Exclude VCS Iignored Paths" with no change. I may fiddle
with it and see if i can find any more clues.  Thanks.

On Sun, Nov 20, 2016, 7:52 PM Alexander Dvinsky <notifications@github.com>
wrote:

@leeahoward <https://github.com/leeahoward> Could it be that all of your
project files are .gitignored? You can try unchecking the "Exclude VCS
Iignored Paths" in Atom's core settings and see whether it helps.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/nuclide/issues/843#issuecomment-261819810>,
or mute
the thread

**Comment by jesseschalken** [comment]
@leeahoward @shushz That fixed it. My home dir is a Git repo with a `.gitignore` that ignores everything ([link](https://github.com/jesseschalken/dotfiles/blob/master/.gitignore)), and my project repo is directly inside my home dir, so Atom hides it because it is hidden by the repo it is inside of. That's definitely a bug - a project root should never be hidden.

Moving the project one level deeper fixes it, but I'm not sure why, since it's still effectively ignored by the outer repo. Probably just a quirk of how Atom handles `.gitignore`s.
