### ISSUE TITLE
BROKEN Split Right/Left from Uncommited Changes in File Tree

### ISSUE THREAD

**Issue by Falieson** [facebook/nuclide#992]
### Issue and Steps to Reproduce
Right clicking on a file in uncommited changes
Select Split Left or Split Right

### Expected Behavior
Open the file to the left or right of an existing file in the editor pane

### Actual Behavior
Open the file to the left or right of the file tree in the file tree pane

### Versions
* Atom: 1.13.0
* Nuclide: 0.200.0
* Client OS: OSX 10.11.6

### Additional Details
* Installed packages (`apm ls --installed`):

├── autocomplete-modules@1.6.7
├── color-picker@2.2.4
├── docblockr@0.9.1
├── editorconfig@2.2.0
├── export-html@3.1.0
├── file-bookmark@1.0.2
├── git-diff-details@1.4.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.12.0
├── language-babel@2.49.4
├── language-freemarker@0.2.0
├── language-graphql@0.8.0
├── language-ini@1.17.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@1.11.21
├── linter-eslint@8.0.0
├── linter-stylelint@3.7.0
├── merge-conflicts@1.4.4
├── nuclide@0.200.0
├── nuclide-format-js@0.0.36
├── react@0.16.2
├── react-snippets@0.5.0
├── regex-railroad-diagram@0.16.0
├── scratch@1.2.0
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── split-diff@1.1.1
├── todo-show@1.9.0
├── tool-bar@1.0.1
└── webbox-color@0.5.9

**Comment by Merajul** [comment]
its ok


Get Outlook for Android






On Fri, Jan 20, 2017 at 11:57 PM +0600, "Falieson" <notifications@github.com> wrote:










Issue and Steps to Reproduce


Right clicking on a file in uncommited changed

Select Split Left or Split Right
Expected Behavior


Open the file to the left or right of an existing file in the editor pane
Actual Behavior


Open the file to the left or right of the file tree in the file tree pane
Versions

Atom: 1.13.0
Nuclide: 0.200.0
Client OS: 10.11.6

Additional Details

Installed packages (apm ls --installed):



├── autocomplete-modules@1.6.7

├── color-picker@2.2.4

├── docblockr@0.9.1

├── editorconfig@2.2.0

├── export-html@3.1.0

├── file-bookmark@1.0.2

├── git-diff-details@1.4.0

├── haskell-grammar@0.4.0

├── highlight-selected@0.12.0

├── language-babel@2.49.4

├── language-freemarker@0.2.0

├── language-graphql@0.8.0

├── language-ini@1.17.0

├── language-lua@0.9.11

├── language-ocaml@1.1.2

├── language-swift@0.5.0

├── language-thrift@1.0.2

├── linter@1.11.21

├── linter-eslint@8.0.0

├── linter-stylelint@3.7.0

├── merge-conflicts@1.4.4

├── nuclide@0.200.0

├── nuclide-format-js@0.0.36

├── react@0.16.2

├── react-snippets@0.5.0

├── regex-railroad-diagram@0.16.0

├── scratch@1.2.0

├── set-syntax@0.3.2

├── sort-lines@0.14.0

├── split-diff@1.1.1

├── todo-show@1.9.0

├── tool-bar@1.0.1

└── webbox-color@0.5.9

**Comment by shushz** [comment]
Yeah, the file-tree has recently moved into a pane and we inherited these context items from it. It should be fixed (removed) in the next release.
